### PR TITLE
Fixed errant operator

### PR DESCRIPTION
**Pull request by BenjiFuse**

### CODE REVIEW

**Comment by A-Dyar** [comment]
JUST RAN INTO THIS

IF YOU HAVE URL THIS MAKES IT 0 INSTEAD OF MY STRING

BIG DUMB

**Comment by mooror** [comment]
@BenjiFuse I have merged in your fix. Thank you for contributing
@A-Dyar I apologize for the delay on this, I haven't been as active on this repository lately

**Comment by A-Dyar** [comment]
> @A-Dyar I apologize for the delay on this, I haven't been as active on this repository lately

That's alright, would you mind if I contributed to the readme? There were a couple of snags I ran into but was successful in a deployment.

**Comment by mooror** [comment]
> That's alright, would you mind if I contributed to the readme? There were a couple of snags I ran into but was successful in a deployment.

I wouldn't mind at all Austin (@A-Dyar), please do. 

I haven't been able to work on this as much as I've been wanting to, and perhaps your README updates will help someone else to successfully setup this project.

**Pull request merged**
